apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: helmfile-controller
    app.kubernetes.io/part-of: flux-helmfile-controller
    app.kubernetes.io/version: v0.0.1
    control-plane: controller
  name: helmfile-controller
  namespace: flux-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: helmfile-controller
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: helmfile-controller
    app.kubernetes.io/part-of: flux-helmfile-controller
    app.kubernetes.io/version: v0.0.1
    control-plane: controller
  name: helmfile-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmfile-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: helmfile-controller
    spec:
      containers:
      - name: controller
        env:
        - name: TEMP_DIR
          value: /tmp/
        image: ghcr.io/swoehrl-mw/flux-helmfile-controller:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      priorityClassName: system-cluster-critical
      securityContext:
        fsGroup: 1000
      serviceAccountName: helmfile-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: tmp
