apiVersion: v1
kind: Secret
metadata:
  name: demo
  namespace: default
type: Opaque
data:
  some_secret: {{ .Values.some_secret_value | b64enc }}
  other_secret: {{ .Values.other_secret_value | b64enc }}
